INSERT INTO estado (id_estado, nombre) VALUES 
 (1, 'AGUASCALIENTES'),  
 (2, 'BAJA CALIFORNIA'),  
 (3, 'BAJA CALIFORNIA SUR'),  
 (4, 'CHIHUAHUA'),  
 (5, 'CHIAPAS'),  
 (6, 'CAMPECHE'),  
 (7, 'CIUDAD DE MEXICO'),  
 (8, 'COAHUILA'),  
 (9, 'COLIMA'),  
 (10, 'DURANGO'),  
 (11, 'GUERRERO'),  
 (12, 'GUANAJUATO'),  
 (13, 'HIDALGO'),  
 (14, 'JALISCO'),  
 (15, 'MICHOACAN'),  
 (16, 'ESTADO DE MEXICO'),  
 (17, 'MORELOS'),  
 (18, 'NAYARIT'),  
 (19, 'NUEVO LEON'),  
 (20, 'OAXACA'),  
 (21, 'PUEBLA'),  
 (22, 'QUINTANA ROO'),  
 (23, 'QUERETARO'),  
 (24, 'SINALOA'),  
 (25, 'SAN LUIS POTOSI'),  
 (26, 'SONORA'),  
 (27, 'TABASCO'),  
 (28, 'TLAXCALA'),  
 (29, 'TAMAULIPAS'),  
 (30, 'VERACRUZ'),  
 (31, 'YUCATAN'),  
 (32, 'ZACATECAS');