import Head from "next/head";
import styles from "../styles/Home.module.css";
import InputButtonComponent from "../components/InputButton/index";
import FooterComponent from "../components/Footer/index";
import SingleStatComponent from "../components/Statistics/index";
import UserIconComponent from "../components/Icon/index";

// import Image from "next/image";
import Header from "../components/header";
import Input from "../components/input";
import Jugador from "../components/jugador";
import Button from "../components/button";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Header />
      <Input />
      <Jugador />
      <Button />
    </div>
    <main className={styles.main}>
        <InputButtonComponent
          name="codigo"
          placeholder="Ingresa codigo"
          content="Registro"
        />
        <SingleStatComponent pj={20} pg={20} pp={20} pe={20} nj={20} />
        <UserIconComponent />
      </main>

      <footer>
        <FooterComponent> </FooterComponent>
      </footer>
  );
}
