import Head from "next/head";
import InputButtonComponent from "../components/InputButton/index";
import Footer from "../components/Footer/index";
import SingleStatComponent from "../components/Statistics/index";
import UserIconComponent from "../components/Icon/index";
// import Image from "next/image";
import Navbar from "../components/Navbar";
import Input from "../components/Input";
import Jugador from "../components/Jugador";
import Button from "../components/Button";

export default function Home() {
  return (
    <>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta
            name="description"
            content="Generated by create next app"
          />
          <link
            rel="icon"
            href="/favicon.ico"
          />
        </Head>
        <Navbar />
        <Input />
        <Jugador />
        <Button />
      </div>
      <div>
        <InputButtonComponent
          name="codigo"
          placeholder="Ingresa"
          content="Registro"
        />
        <SingleStatComponent
          pj={20}
          pg={20}
          pp={20}
          pe={20}
          nj={20}
        />
        <UserIconComponent />
      </div>

      <footer>
        <Footer> </Footer>
      </footer>
    </>
  );
}
